tasks:
  - name: add-comment
    on:
      issues:
        types: [labeled]
    condition: 'payload.label.name == "wrong repo"'
    config:
      close: true
      lock: true
      comment: |
        This issue doesn't appear to be an issue with the Capacitor site or documentation. Please [use this form](https://github.com/ionic-team/capacitor/issues/new/choose) to refile your issue elsewhere.

        Thanks!
        Ionitron 💙
  - name: assign-to-project
    on:
      issues:
        types: [opened]
      pull_request:
        types: [opened]
    condition: (await getTeamMembers('capacitor')).includes(payload.sender.login)
    config:
      columns:
        issue: 10495656
        pr: 10495659
        draft-pr: 10495658
