name: Capacitor Bot

on:
  issues:
    types: [labeled]

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ionic-team/bot@main
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
